# Generated by Django 4.2.3 on 2023-07-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckupApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='ip_address',
            field=models.CharField(max_length=20),
        ),
    ]
