# Generated by Django 4.2.3 on 2023-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckupApp', '0003_servercheckresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servercheckresult',
            name='status_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='ip_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
