# Generated by Django 4.2.3 on 2023-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckupApp', '0004_alter_servercheckresult_status_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servercheckresult',
            name='server_stauts',
            field=models.BooleanField(default=True),
        ),
    ]
