# Generated by Django 4.2.3 on 2023-07-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckupApp', '0005_servercheckresult_server_stauts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servercheckresult',
            name='server_stauts',
            field=models.IntegerField(default=1),
        ),
    ]
